# Use an official Node.js runtime as a parent image
FROM node:20.14.0 AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the TypeScript source code
COPY . .

# Compile the TypeScript code
RUN npm run build

# Use a smaller image for production
FROM node:22-slim

ENV NODE_ENV=production

# Set the working directory in the container
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/config/.env.production ./config/.env.production
COPY --from=builder /app/config.js ./

# Expose the port the app runs on
EXPOSE 8081

# Command to run the application
CMD ["node", "-r", "./config.js", "./dist"]